import { useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import {
  Activity,
  Shield,
  HelpCircle,
  FileText,
  Edit3,
  Download,
  Zap,
  ChevronRight,
  ArrowDown,
} from "lucide-react";

/* ── Particles Background ── */
function Particles() {
  const particles = [
    { left: "10%", top: "20%", delay: "0s", duration: "25s" },
    { left: "30%", top: "60%", delay: "-5s", duration: "20s" },
    { left: "60%", top: "30%", delay: "-10s", duration: "30s" },
    { left: "80%", top: "70%", delay: "-15s", duration: "22s" },
    { left: "50%", top: "10%", delay: "-8s", duration: "28s" },
    { left: "90%", top: "50%", delay: "-3s", duration: "18s" },
  ];

  return (
    <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
      {particles.map((p, i) => (
        <div
          key={i}
          className="absolute w-[3px] h-[3px] bg-accent rounded-full opacity-20"
          style={{
            left: p.left,
            top: p.top,
            animation: `float-particle ${p.duration} ${p.delay} infinite linear`,
          }}
        />
      ))}
    </div>
  );
}


function Navbar() {
  const navRef = useRef(null);

  useEffect(() => {
    const handleScroll = () => {
      if (navRef.current) {
        navRef.current.classList.toggle("bg-bg/85", window.scrollY > 50);
        navRef.current.classList.toggle(
          "backdrop-blur-xl",
          window.scrollY > 50,
        );
        navRef.current.classList.toggle("border-b", window.scrollY > 50);
        navRef.current.classList.toggle("border-border", window.scrollY > 50);
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <nav
      ref={navRef}
      className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-10 py-4 transition-all duration-300"
    >
      <div className="flex items-center gap-2.5">
        <div className="flex items-center justify-center w-[34px] h-[34px] bg-gradient-to-br from-accent to-purple-600 rounded-[10px] text-white">
          <Activity size={20} />
        </div>
        <span className="font-bold text-[1.1rem] tracking-tight">
          ThyroPredict
        </span>
      </div>
      <div className="hidden md:flex gap-8">
        <a
          href="#about"
          className="text-text-secondary text-sm font-medium hover:text-text-primary transition-colors"
        >
          About
        </a>
        <a
          href="#features"
          className="text-text-secondary text-sm font-medium hover:text-text-primary transition-colors"
        >
          Features
        </a>
        <a
          href="#how-it-works"
          className="text-text-secondary text-sm font-medium hover:text-text-primary transition-colors"
        >
          How It Works
        </a>
      </div>
    </nav>
  );
}


function useScrollAnimation() {
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("animate-in");
          }
        });
      },
      { threshold: 0.1, rootMargin: "0px 0px -50px 0px" },
    );

    document.querySelectorAll(".animate-target").forEach((el) => {
      observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);
}


export default function LandingPage() {
  useScrollAnimation();

  const aboutCards = [
    {
      icon: <Shield size={24} />,
      title: "Clinically Informed",
      description:
        "Built on real-world thyroid cancer datasets with carefully engineered features for maximum predictive power.",
      colorClass: "",
    },
    {
      icon: <HelpCircle size={24} />,
      title: "Explainable AI",
      description:
        "Every prediction comes with a plain-language explanation — no confusing medical codes or jargon.",
      colorClass: "teal",
    },
    {
      icon: <FileText size={24} />,
      title: "PDF Reports",
      description:
        "Generate and download beautifully formatted clinical-style PDF reports for your records.",
      colorClass: "amber",
    },
  ];

  const features = [
    {
      title: "Machine Learning Prediction",
      description:
        "Our Random Forest classifier is trained on comprehensive thyroid cancer data, achieving high accuracy in recurrence prediction.",
    },
    {
      title: "AI-Powered Explanations",
      description:
        "Each prediction includes a compassionate, easy-to-understand explanation tailored for patients, generated by advanced AI.",
    },
    {
      title: "Instant Results",
      description:
        "Get your prediction, explanation, and downloadable PDF report in seconds — no waiting, no complexity.",
    },
    {
      title: "Privacy First",
      description:
        "Your data is never stored. Each prediction is processed in real-time and discarded after generating your report.",
    },
  ];

  const steps = [
    {
      icon: <Edit3 size={28} />,
      title: "Enter Patient Data",
      description:
        "Fill in clinical details like age, gender, and risk level in our simple form.",
      colorClass: "",
    },
    {
      icon: <Activity size={28} />,
      title: "AI Analysis",
      description:
        "Our model processes the data and AI generates a clear, human-readable explanation.",
      colorClass: "teal",
    },
    {
      icon: <Download size={28} />,
      title: "Download Report",
      description:
        "View your detailed results and download a professionally formatted PDF report.",
      colorClass: "amber",
    },
  ];

  return (
    <div className="overflow-x-hidden">
      <Particles />
      <Navbar />

      {/* ── Hero Section ── */}
      <section className="relative min-h-screen flex items-center justify-center px-8 pt-24 pb-16 text-center overflow-hidden">
        {/* Glow */}
        <div className="absolute top-[15%] left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-[radial-gradient(ellipse,rgba(99,102,241,0.12)_0%,transparent_70%)] pointer-events-none z-0" />

        <div className="relative z-10 max-w-[720px]">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-accent/10 border border-accent/20 rounded-full text-[0.8rem] font-medium text-accent-hover mb-6">
            <span
              className="w-1.5 h-1.5 bg-accent rounded-full"
              style={{ animation: "pulse-dot 2s ease-in-out infinite" }}
            />
            AI-Powered Clinical Analysis
          </div>

          <h1 className="text-[clamp(2.5rem,6vw,3.8rem)] font-extrabold leading-[1.15] tracking-tight mb-5">
            Thyroid Cancer
            <br />
            <span className="gradient-text">Recurrence Predictor</span>
          </h1>

          <p className="text-[1.1rem] text-text-secondary leading-relaxed max-w-[580px] mx-auto mb-8">
            Harness the power of machine learning to predict the likelihood of
            thyroid cancer recurrence. Our AI model analyzes patient data to
            deliver instant, explainable clinical insights — empowering both
            patients and healthcare professionals.
          </p>

          <div className="flex items-center justify-center gap-4 mb-12 flex-wrap">
            <Link
              to="/predict"
              className="inline-flex items-center gap-2 px-7 py-3 bg-gradient-to-br from-accent to-purple-600 text-white rounded-xl text-[1.05rem] font-semibold shadow-[0_4px_20px_rgba(99,102,241,0.3)] hover:-translate-y-0.5 hover:shadow-[0_8px_30px_rgba(99,102,241,0.45)] transition-all duration-300 no-underline"
            >
              <Zap size={20} />
              Get Started
            </Link>
            <a
              href="#about"
              className="inline-flex items-center gap-1.5 px-6 py-3 border border-border rounded-xl text-text-secondary text-[0.95rem] font-medium hover:text-text-primary hover:border-text-muted hover:bg-white/[0.03] transition-all duration-300 no-underline"
            >
              Learn More
              <ArrowDown size={16} />
            </a>
          </div>

          {/* Stats */}
          <div className="flex items-center justify-center gap-8 px-8 py-5 bg-white/[0.02] border border-border rounded-2xl backdrop-blur-lg flex-wrap">
            <div className="flex flex-col items-center gap-0.5">
              <span className="text-[1.4rem] font-extrabold text-accent-hover tracking-tight">
                95%+
              </span>
              <span className="text-[0.75rem] text-text-muted font-medium uppercase tracking-wider">
                Model Accuracy
              </span>
            </div>
            <div className="w-px h-9 bg-border hidden sm:block" />
            <div className="flex flex-col items-center gap-0.5">
              <span className="text-[1.4rem] font-extrabold text-accent-hover tracking-tight">
                &lt;5s
              </span>
              <span className="text-[0.75rem] text-text-muted font-medium uppercase tracking-wider">
                Prediction Time
              </span>
            </div>
            <div className="w-px h-9 bg-border hidden sm:block" />
            <div className="flex flex-col items-center gap-0.5">
              <span className="text-[1.4rem] font-extrabold text-accent-hover tracking-tight">
                AI
              </span>
              <span className="text-[0.75rem] text-text-muted font-medium uppercase tracking-wider">
                Smart Analysis
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* ── About Section ── */}
      <section id="about" className="py-20 px-8">
        <div className="max-w-[900px] mx-auto">
          <span className="animate-target inline-block px-3.5 py-1.5 bg-accent/10 border border-accent/15 rounded-full text-[0.78rem] font-semibold text-accent uppercase tracking-widest mb-4">
            About the Project
          </span>
          <h2 className="animate-target text-[clamp(1.6rem,4vw,2.2rem)] font-extrabold tracking-tight mb-4">
            What is ThyroPredict?
          </h2>
          <p className="animate-target text-[1.02rem] text-text-secondary leading-relaxed max-w-[680px] mb-10">
            ThyroPredict is an AI-driven tool designed to help assess the risk
            of thyroid cancer recurrence. By analyzing key patient clinical
            features such as age, gender, risk classification, and other medical
            parameters, our trained Random Forest model provides a
            probability-based prediction along with a detailed, human-readable
            explanation generated by Google's Gemini AI.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {aboutCards.map((card, i) => (
              <div
                key={i}
                className="animate-target bg-card border border-card-border rounded-2xl p-7 transition-all duration-300 hover:border-accent/30 hover:-translate-y-1 hover:shadow-[0_12px_40px_rgba(0,0,0,0.3)]"
              >
                <div
                  className={`flex items-center justify-center w-11 h-11 rounded-xl mb-4 ${
                    card.colorClass === "teal"
                      ? "bg-accent-teal/[0.12] text-accent-teal"
                      : card.colorClass === "amber"
                        ? "bg-accent-amber/[0.12] text-accent-amber"
                        : "bg-accent-glow text-accent"
                  }`}
                >
                  {card.icon}
                </div>
                <h3 className="text-base font-bold mb-2">{card.title}</h3>
                <p className="text-sm text-text-secondary leading-relaxed">
                  {card.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features Section ── */}
      <section id="features" className="py-20 px-8 bg-bg-secondary">
        <div className="max-w-[900px] mx-auto">
          <span className="animate-target inline-block px-3.5 py-1.5 bg-accent/10 border border-accent/15 rounded-full text-[0.78rem] font-semibold text-accent uppercase tracking-widest mb-4">
            Features
          </span>
          <h2 className="animate-target text-[clamp(1.6rem,4vw,2.2rem)] font-extrabold tracking-tight mb-10">
            Why Choose ThyroPredict?
          </h2>

          <div className="flex flex-col">
            {features.map((feat, i) => (
              <div
                key={i}
                className="animate-target flex items-start gap-6 py-6 border-b border-border last:border-b-0"
              >
                <div className="text-[2rem] font-extrabold text-accent/20 min-w-[60px] tracking-tight leading-none pt-0.5">
                  {String(i + 1).padStart(2, "0")}
                </div>
                <div>
                  <h3 className="text-[1.05rem] font-bold mb-1">
                    {feat.title}
                  </h3>
                  <p className="text-[0.92rem] text-text-secondary leading-relaxed">
                    {feat.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works Section ── */}
      <section id="how-it-works" className="py-20 px-8">
        <div className="max-w-[900px] mx-auto">
          <span className="animate-target inline-block px-3.5 py-1.5 bg-accent/10 border border-accent/15 rounded-full text-[0.78rem] font-semibold text-accent uppercase tracking-widest mb-4">
            How It Works
          </span>
          <h2 className="animate-target text-[clamp(1.6rem,4vw,2.2rem)] font-extrabold tracking-tight mb-10">
            Three Simple Steps
          </h2>

          <div className="flex items-start justify-center gap-0 flex-col md:flex-row">
            {steps.map((step, i) => (
              <div key={i} className="flex items-start md:items-center">
                <div className="animate-target relative bg-card border border-card-border rounded-2xl p-8 text-center flex-1 max-w-[240px] w-full transition-all duration-300 hover:border-accent/30 hover:-translate-y-1">
                  {/* Step Number */}
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 w-[26px] h-[26px] bg-accent text-white text-[0.75rem] font-bold flex items-center justify-center rounded-full">
                    {i + 1}
                  </div>
                  <div
                    className={`inline-flex items-center justify-center w-14 h-14 rounded-2xl mb-4 ${
                      step.colorClass === "teal"
                        ? "bg-accent-teal/10 text-accent-teal"
                        : step.colorClass === "amber"
                          ? "bg-accent-amber/10 text-accent-amber"
                          : "bg-accent-glow text-accent"
                    }`}
                  >
                    {step.icon}
                  </div>
                  <h3 className="text-[0.95rem] font-bold mb-2">
                    {step.title}
                  </h3>
                  <p className="text-[0.85rem] text-text-secondary leading-relaxed">
                    {step.description}
                  </p>
                </div>
                {i < steps.length - 1 && (
                  <div className="hidden md:flex items-center pt-10 opacity-40 mx-1">
                    <ChevronRight size={24} className="text-accent" />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Section ── */}
      <section className="relative py-20 px-8 text-center overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[300px] bg-[radial-gradient(ellipse,rgba(99,102,241,0.08)_0%,transparent_70%)] pointer-events-none" />
        <div className="relative z-10">
          <h2 className="text-[clamp(1.5rem,4vw,2rem)] font-extrabold mb-3 tracking-tight">
            Ready to Get Your Prediction?
          </h2>
          <p className="text-text-secondary text-base mb-8">
            It only takes a minute. Enter patient details and let our AI do the
            rest.
          </p>
          <Link
            to="/predict"
            className="inline-flex items-center gap-2 px-9 py-4 bg-gradient-to-br from-accent to-purple-600 text-white rounded-xl text-[1.05rem] font-semibold shadow-[0_4px_20px_rgba(99,102,241,0.3)] hover:-translate-y-0.5 hover:shadow-[0_8px_30px_rgba(99,102,241,0.45)] transition-all duration-300 no-underline"
          >
            <Zap size={20} />
            Get Started Now
          </Link>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-border py-8 px-8">
        <div className="max-w-[900px] mx-auto flex items-center justify-between flex-col md:flex-row gap-4">
          <div className="flex items-center gap-2 font-semibold text-sm">
            <div className="flex items-center justify-center w-[34px] h-[34px] bg-gradient-to-br from-accent to-purple-600 rounded-[10px] text-white">
              <Activity size={16} />
            </div>
            <span>ThyroPredict</span>
          </div>
          <p className="text-[0.75rem] text-text-muted max-w-[400px] text-center md:text-right leading-relaxed">
            This tool is for informational purposes only and does not constitute
            medical advice. Always consult a qualified healthcare professional.
          </p>
        </div>
      </footer>
    </div>
  );
}
